### ISSUE TITLE
plugin broken with ST3?

### ISSUE THREAD

**Issue by johnathanz** [rodcloutier/Vintageous-Origami#14]
Hey Rod

I tested this plugin on the latest stable Beta build of ST3 (build 3065).  A few controls work, others don't.

I have Vintageous and Origami installed,  and option: "vintageous_use_ctrl_keys" is set to true.

WORKS:
v ctrl+v: Vertical split
c: Close pane
o ctrl+o: Make current pane the only one
l, <right>: Move to right pane
h, <left>: Move to left pane

DOESN'T WORK:
s S ctrl+s: Horizontal split
n ctrl+n: New horizontal split with empty file
k, <up>: Move to up pane
j, <down>: Move to down pane
L: Exchange with right pane
H: Exchange with left pane
K: Exchange with up pane
J: Exchange with down pane
x: Close window
X: Close all windows
The commands also don't work
:vs[plit]: Vertical split
:sp[lit]: Horizontal split
:new: Horizontal split with new file
:vne[w]: Vertical split with new file
:on[ly]: Make current pane the only one

Any help is appreciated!

**Comment by gerardroche** [comment]
I cannot reproduce this on Linux / ST3 build 3065 / Vintageous ~3

**Comment by guoqiao** [comment]
Doesn't work for me, either.  Mac OS X 10.10.5, Sublime Text 3, Stable Channel, Build 3083. 
Vintage in disabled_packages, Vintageous and Origami Installed,  vintageous_use_ctrl_keys = true

**Comment by brandon-carag** [comment]
Doesn't work for me either--I can jump between panes using control-w and then a movement key, but not having much luck opening up new panes.

**Comment by thashepherd** [comment]
Try using this fork: https://github.com/jlangston/Vintageous-Origami

**Comment by rodcloutier** [comment]
I just created a new branch with support for Vintageous 4. I will do some cleanup and submit a new version soon.

**Comment by rodcloutier** [comment]
Just pushed the new version 2.0.0 with support for Vintageous 4
