### ISSUE TITLE
Stops working with latest Vintageous 4 release

### ISSUE THREAD

**Issue by gerardroche** [rodcloutier/Vintageous-Origami#15]
Linux / ST3 build 3065 / Vintageous ~4.0

Console log on startup

```
reloading plugin VintageousOrigami.action_cmds
reloading plugin VintageousOrigami.xactions
Traceback (most recent call last):
  File "/home/user/sublime_text_3/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/user/sublime_text_3/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "xactions in /home/user/.config/sublime-text-3/Installed Packages/VintageousOrigami.sublime-package", line 106, in <module>
ImportError: No module named 'Vintageous.ex.ex_command_parser'
```

See also https://github.com/guillermooo/Vintageous/issues/903

_This is a very good example of why package version dependency management would be a very good thing. Ping https://github.com/SublimeTextIssues/Core/issues/615_

**Comment by rodcloutier** [comment]
Hi, I am not using Sublime anymore. If you want interested in keeping the project alive, let me know.

**Comment by hpoydar** [comment]
Yeah, I'm interested

**Comment by roganov** [comment]
May I ask what editor you ended up using? I suppose Vim?

**Comment by hpoydar** [comment]
I still use Sublime as my primary editor. For now I'm just using the last version of Vintageous that works with VintageousOrigami.

**Comment by jlangston** [comment]
I was able to get most of the functionality restored by commenting out the ex commands. They need to be updated to the new way Vintageous handles ex commands. I haven't made it that far and I don't use the ex commands very frequently and also some of them are already mapped in Vintageous. If I can find some time to look at them I'll see if I can update the ex commands and submit a pull request but for my general usage I have it working for me.  See https://github.com/jlangston/Vintageous-Origami

**Comment by brandon-carag** [comment]
Thanks for the simple fork @jlangston .  The commented code looks to have restored much of the functionality for me as well and I'm using Sublime Text 3 (Build 3103)

**Comment by rodcloutier** [comment]
I just created a new branch with support for Vintageous 4. I will do some cleanup and submit a new version soon.

**Comment by rodcloutier** [comment]
Just push the new version 2.0.0 with support for Vintageous 4
