### ISSUE TITLE
Tagged based releases

### ISSUE THREAD

**Issue by gerardroche** [rodcloutier/Vintageous-Origami#16]
Start using tagged based releases. 

One reason is that the recent release of Vintageous 4 broke Vintageous Origami. My suggestion is to: 
- Subscribe to a [semver](http://semver.org/)  versioning policy
- Tag this current version as `1.0.0` and create a `release-1.0.0` branch 
- Update package control channel to use tagged based releases https://github.com/wbond/package_control_channel/blob/c478a5db83a20bf318dc7805e14c292360d98dc4/repository/v.json#L323
- Update Vintageous Origami to work with Vintageous 4 and tag as `2.0.0`

Ping https://github.com/rodcloutier/Vintageous-Origami/issues/15

**Comment by rodcloutier** [comment]
Good idea. I just created a new branch with support for Vintageous 4. I will do some cleanup and submit a new version soon using tagged based releases.

Thank for the pointer for package control. I will have a look.

**Comment by rodcloutier** [comment]
Just push the new version 2.0.0 with support for Vintageous 4. 
Also submitted a PR to move to tag based releases. Waiting on merge in package control channel.
