### ISSUE TITLE
:only no longer works

### ISSUE THREAD

**Issue by quarterto** [rodcloutier/Vintageous-Origami#18]
Instead of closing all other panes, it just closes all *files* in other panes, leaving the panes intact.

**Comment by quarterto** [comment]
Oh, it looks like Vintageous has an `:only` command [built in](https://github.com/guillermooo/Vintageous/blob/master/ex/parser/scanner_command_only.py) now. Is there any way to override an ex command?

**Comment by rodcloutier** [comment]
I have added the feature in 2.0.0. You can change the default behaviour by using the following option
`"vintageous_origami_override_command_only": false`
